import torch
import torch.nn as nn
import os
import matplotlib.pyplot as plt
import numpy as np
from functools import partial
# Import your new Anomaly Detection Runner and Metrics
from ..base_adt_runner import AnomalyDetectionRunner 
from detection.metric import detection_accuracy, detection_precision, detection_recall, detection_f1, detection_auc

class iTransformer2AnomalyRunner(AnomalyDetectionRunner):
    """
    Runner for Global Anomaly Detection using iTransformer.
    Predicts a binary label (0 or 1) indicating if an anomaly will occur in the future window.
    """

    def __init__(self, cfg: dict):
        super().__init__(cfg)
        # 1. Completely Replace Metrics with Classification Metrics
        self.metrics = {
            "Accuracy": partial(detection_accuracy, task='global'),
            "F1": partial(detection_f1, task='global'),
            "AUC": partial(detection_auc, task='global'),
            # Local (Stock-Specific) Metrics
            "Local_Accuracy": partial(detection_accuracy, task='local'),
            "Local_Precision": partial(detection_precision, task='local'),
            "Local_Recall": partial(detection_recall, task='local'),
            "Local_F1": partial(detection_f1, task='local'),
            "Local_AUC": partial(detection_auc, task='local'),        
        }
        self.use_local=True
        # 2. Forward features (Target features are removed since we predict a single label, not a sequence)
        self.forward_features = cfg["MODEL"].get("FORWARD_FEATURES", None)

        # Re-initialize weights for the Transformer
        for p in self.model.parameters():
            if p.dim() > 1:
                nn.init.xavier_uniform_(p)
            else:
                nn.init.uniform_(p)

    def select_input_features(self, data: torch.Tensor) -> torch.Tensor:
        """Select input features (e.g., picking just the 'close' price if C > 1)."""
        if self.forward_features is not None:
            data = data[:, :, :, self.forward_features]
        return data

    def _visualize_results(self, history, logits, labels, epoch):
        """
        Visualizes the input sequence and the model's binary prediction.
        history: [B, L, N, C]
        logits: [B, 1]
        labels: [B, 1]
        """
        save_path = os.path.join(self.ckpt_save_dir, 'plots')
        os.makedirs(save_path, exist_ok=True)

        # 1. Get the first sample in the batch
        # Calculate the market average across all N nodes for the plot
        hist_avg = history[0, :, :, 0].mean(dim=-1).detach().cpu().numpy()
        
        # 2. Extract Prediction and Target
        prob = torch.sigmoid(logits[0]).detach().cpu().item()
        pred_class = 1 if prob > 0.5 else 0
        true_class = int(labels[0].detach().cpu().item())

        # 3. Plot
        plt.figure(figsize=(10, 5))
        x_hist = np.arange(len(hist_avg))
        plt.plot(x_hist, hist_avg, label='Market Average (History)', color='blue', linewidth=2)

        # Color code the title: Green if correct, Red if wrong
        title_color = 'green' if pred_class == true_class else 'red'
        title_text = f"Epoch {epoch} | Target: {true_class} | Pred: {pred_class} (Prob: {prob:.2f})"
        
        plt.title(title_text, color=title_color, fontweight='bold')
        plt.xlabel("Time Steps")
        plt.ylabel("Normalized Average Price")
        plt.axvline(x=len(hist_avg)-1, color='gray', linestyle=':', label='Forecast Point')
        plt.grid(True, linestyle='--', alpha=0.5)
        plt.legend()
        
        plt.savefig(os.path.join(save_path, f"epoch_{epoch}_anomaly_val.png"))
        plt.close()

    def forward(self, data: tuple, epoch: int = None, iter_num: int = None, train: bool = True, **kwargs) -> tuple:
        """
        Feed forward process for train, val, and test.
        Args:
            data (tuple): (history_data, labels) generated by AnomalyDetectionDataset
        Returns:
            tuple: (logits, labels)
        """
        # 1. Preprocess & Unpack (Notice no future_data is unpacked)
        history_data, labels = data
        
        history_data = self.to_running_device(history_data)  # [B, L, N, C]
        labels['global'] = self.to_running_device(labels['global'])              # [B, N]
        labels['local'] = self.to_running_device(labels['local'])              # [B, N]
        # 2. Feature Selection
        # history_data = self.select_input_features(history_data)
        # 3. Model Inference 
        logits = self.model(history_data) 
        # 4. Shape validation to catch architecture mismatches early
        batch_size = history_data.shape[0]
        # assert list(logits.shape) == [batch_size, 1], \
        #     f"Error: Output shape is {logits.shape}, but expected [{batch_size}, 1]. Check the global pooling layer."
        # # 5. Visualization at intervals
        if train and ((iter_num % 1000) == 0) and epoch is not None:
            try:
                self._visualize_results(history_data, logits['global'], labels['global'], epoch)
            except Exception as e:
                print(f"Visualization failed at epoch {epoch}: {e}")

        return logits, labels