import torch
import torch.nn as nn
import torch.nn.functional as F
from .layers.Transformer_EncDec import Encoder, EncoderLayer
from .layers.SelfAttention_Family import FullAttention, AttentionLayer
from .layers.Embed import DataEmbedding_inverted

class iTransformer2AnomalyDetector(nn.Module):
    """
    Adapted iTransformer for Global Time Series Anomaly Detection.
    Converts forecasting sequence-to-sequence into sequence-to-one binary classification.
    """
    def __init__(self, seq_len, d_model, dropout, d_ff, n_heads, e_layers, use_norm):
        super(iTransformer2AnomalyDetector, self).__init__()
        self.seq_len = seq_len
        self.use_norm = use_norm
        
        # Inverted Embedding: Treats each stock's history as a single token
        self.enc_embedding = DataEmbedding_inverted(seq_len, d_model, dropout=dropout)
        
        # Encoder-only architecture
        self.encoder = Encoder(
            [
                EncoderLayer(
                    AttentionLayer(
                        FullAttention(False, attention_dropout=dropout), d_model, n_heads),
                    d_model,
                    d_ff,
                    dropout=dropout,
                ) for l in range(e_layers)
            ],
            norm_layer=torch.nn.LayerNorm(d_model)
        )
        
        # NEW: Anomaly Detection Head
        # Input size is d_model * 2 because we will concatenate Mean and Max pooling
        self.detector = nn.Sequential(
            nn.Linear(d_model, 1),
        )
        self.detector2 = nn.Sequential(
            nn.Linear(d_model * 2, d_model // 2),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(d_model // 2, 1) # Output raw logits [B, 1]
        )

    def detect(self, x_enc):
        # x_enc shape: [B, L, N]
        if self.use_norm:
            # Instance Normalization
            means = x_enc.mean(1, keepdim=True).detach()
            x_enc = x_enc - means
            stdev = torch.sqrt(torch.var(x_enc, dim=1, keepdim=True, unbiased=False) + 1e-5)
            x_enc /= stdev

        # Embedding
        # B L N -> B N E
        enc_out = self.enc_embedding(x_enc) 
        # B N E -> B N E
        enc_out, _ = self.encoder(enc_out, attn_mask=None)
        # Final Classification
        logits_local = self.detector(enc_out).squeeze(-1) # [B, N]
        
        mean_pool = torch.mean(enc_out, dim=1) # [B, E]
        
        # Max Pooling captures the "extreme sector rotations / sudden spikes"
        max_pool = torch.max(enc_out, dim=1)[0] # [B, E]
        
        # Combine both global perspectives
        global_representation = torch.cat([mean_pool, max_pool], dim=-1) # [B, 2 * E]

        # Final Classification
        logits_global = self.detector2(global_representation) # [B, 1]

        logits ={
            'local':logits_local,
            'global':logits_global,
        }
        return logits

    def forward(self, data, epoch=None, iter_num=None, train=True, **kwargs):
        """
        Fits the AnomalyDetectionRunner signature.
        data: Tuple of (history_data, labels) generated by Dataset __getitem__
        """
        # Unpack the tuple from the DataLoader
        history_data = data 
        # history_data comes in as [B, L, N, 1]. Squeeze the feature dim to [B, L, N]
        x_enc = history_data.squeeze(-1)
        # Get predictions
        logits = self.detect(x_enc)
        return logits