import torch
import torch.nn as nn
import torch.nn.functional as F
from .time_encoder import TimeEncoder
from .space_encoder import SpaceEncoder

class NumerMoe(nn.Module):
    """
    Adapted iTransformer for Global Time Series Anomaly Detection.
    Converts forecasting sequence-to-sequence into sequence-to-one binary classification.
    """
    def __init__(self, tim_configs, spc_configs):
        super(NumerMoe, self).__init__()
        d_model = spc_configs["d_model"]
        dropout = spc_configs["dropout"]

        self.temporal = TimeEncoder(tim_configs)
        self.spatial  = SpaceEncoder(spc_configs)
        self.norm = nn.LayerNorm(d_model)
        
        # NEW: Anomaly Detection Head
        # Input size is d_model * 2 because we will concatenate Mean and Max pooling
        self.detector = nn.Sequential(
            nn.Linear(d_model, 1),
            nn.Dropout(dropout // 2),
        )

        self.detector2 = nn.Sequential(
            nn.Linear(d_model * 2, d_model // 2),
            nn.GELU(),
            nn.Dropout(dropout // 2),
            nn.Linear(d_model // 2, 1)
        )

    def detect(self, x_enc):
        x_enc = self.temporal(x_enc)
        x_enc = self.spatial(x_enc)
        x_enc = self.norm(x_enc)
        
        logits_local = self.detector(x_enc).squeeze(-1)

        mean_pool = torch.mean(x_enc, dim=1) # [B, E]
        max_pool = torch.max(x_enc, dim=1)[0] # [B, E]
        global_representation = torch.cat([mean_pool, max_pool], dim=-1) # [B, 2 * E]
        logits_global = self.detector2(global_representation) # [B, 1]
        logits ={
            'local':logits_local,
            'global':logits_global,
        }
        return logits

    def forward(self, data, epoch=None, iter_num=None, train=True, **kwargs):
        """
        Fits the AnomalyDetectionRunner signature.
        data: Tuple of (history_data, labels) generated by Dataset __getitem__
        """
        history_data = data 
        x_enc = history_data.squeeze(-1)
        logits = self.detect(x_enc)
        return logits